from sqlalchemy import Column, Integer, String, Text, DateTime, Float, JSON, Date, BigInteger
from sqlalchemy.sql import func

# Flexible imports that work both locally and in Docker
try:
    # Try relative imports first (for Docker)
    from .db import Base
except ImportError:
    # Fall back to absolute imports (for local development)
    from db import Base


class TdKaryawan(Base):
    """Model for existing td_karyawan table"""
    __tablename__ = "td_karyawan"

    # Primary key
    id_karyawan = Column(Integer, primary_key=True, index=True)
    
    # Basic employee information
    # valdo_inc = Column(String(200), nullable=True)
    # nik_klient = Column(String(200), nullable=True)
    # klient = Column(String(200), nullable=True)
    # placement = Column(String(200), nullable=False)
    # project = Column(String(200), nullable=True)
    # area = Column(String(200), nullable=True)
    # penempatan = Column(String(200), nullable=True)
    # nik = Column(String(200), nullable=False, unique=True)
    # sales_code = Column(String(200), nullable=True)
    # nama = Column(String(200), nullable=True)
    # nama_depan = Column(String(200), nullable=True)
    # nama_belakang = Column(String(200), nullable=True)
    # status_kontrak = Column(String(200), nullable=True)
    # rec_status = Column(String(200), nullable=True)
    # tgl_joint = Column(Date, nullable=True)
    # tgl_joint_valdo = Column(Date, nullable=True)
    # tgl_resign = Column(Date, nullable=True)
    # reason = Column(Text, nullable=True)
    status = Column(String(200), nullable=True)
    # dept_code = Column(String(200), nullable=True)
    # dept = Column(String(200), nullable=True)
    # golongan_id = Column(BigInteger, nullable=True)
    # posisi = Column(String(200), nullable=True)
    # grouping = Column(String(200), nullable=True)
    # gender = Column(String(200), nullable=True)
    # nama_bank = Column(String(200), nullable=True)
    # no_rek = Column(String(200), nullable=True)
    # nama_rek = Column(String(255), nullable=True)
    # len1 = Column(String(10), nullable=True)
    # email = Column(String(150), nullable=True)
    # bpjs_kesehatan = Column(String(100), nullable=True)
    # bpjs_ketenagakerjaan = Column(String(100), nullable=True)
    # npwp = Column(String(100), nullable=True)
    # kk = Column(String(100), nullable=True)
    # ktp = Column(String(100), nullable=True)
    # len2 = Column(String(3), nullable=True)
    # alamat1 = Column(Text, nullable=True)
    # alamat2 = Column(Text, nullable=True)
    # kota = Column(String(100), nullable=True)
    # tlp_rumah = Column(String(100), nullable=True)
    # hp1 = Column(String(150), nullable=True)
    # hp2 = Column(String(150), nullable=True)
    # tmpt_lahir = Column(String(200), nullable=True)
    # tgl_lahir = Column(Date, nullable=True)
    # usia = Column(Integer, nullable=True)
    # agama = Column(String(100), nullable=True)
    # gol_darah = Column(String(3), nullable=True)
    # marital1 = Column(String(50), nullable=True)
    # marital2 = Column(String(50), nullable=True)
    # eoc = Column(Date, nullable=True)
    # no_kontrak_terakhir = Column(String(100), nullable=True)
    # gaji = Column(Integer, nullable=True)
    # id_admin = Column(String(10), nullable=True)
    # user_create = Column(String(100), nullable=True)
    # tgl_create = Column(DateTime, nullable=True)
    # user_edit = Column(String(100), nullable=True)
    # tgl_edit = Column(Date, nullable=True)
    # keterangan = Column(Text, nullable=True)
    # pid = Column(String(30), nullable=False)
    # level = Column(String(50), nullable=False)
    # leader = Column(String(100), nullable=False)
    # supervisor = Column(String(100), nullable=False)
    # password = Column(String(250), nullable=False)
    # temp_password = Column(String(250), nullable=False)
    # first_login = Column(String(1), nullable=False)
    # reset_password = Column(Integer, nullable=False)
    # reset_location = Column(Integer, nullable=False, default=0)
    # aktif = Column(String(1), nullable=False)
    # versi = Column(String(20), nullable=False)
    # website = Column(String(20), nullable=False)
    # token = Column(String(255), nullable=False)
    # home_latitude = Column(String(100), nullable=False)
    # home_longitude = Column(String(100), nullable=False)
    # notification_token = Column(Text, nullable=False)
    # working = Column(Integer, nullable=False)
    # foto = Column(String(255), nullable=False)
    # annual_leave = Column(Integer, nullable=False, default=0)
    # overtime_available = Column(Integer, nullable=False, default=9)
    # expired_date = Column(DateTime, nullable=False)
    # temp_address = Column(Text, nullable=False)
    # temp_home_latitude = Column(String(100), nullable=False)
    # temp_home_longitude = Column(String(100), nullable=False)
    # status_hr = Column(String(10), nullable=False)
    # created_status_hr = Column(DateTime, nullable=False)
    # tgl_gajian = Column(String(10), nullable=False)
    loan_kasbon_eligible = Column(Integer, nullable=False)
    # loan_popup_show = Column(Integer, nullable=False, default=0)
    # juragan_beku_popup_show = Column(Integer, nullable=False)
    # company_type = Column(Integer, nullable=False)
    # forgot_password_request = Column(DateTime, nullable=True)
    # recruitment_id = Column(Integer, nullable=True)
    # new_hire_param = Column(Integer, nullable=False)
    # new_hire_notes = Column(Text, nullable=True)
    # deleted_at = Column(DateTime, nullable=True)


